### ISSUE TITLE
移动端适配问题

### ISSUE THREAD

**Issue by chenbo29** [fecommunity/reactpress#4]
微信端打开 https://blog.gaoredu.com/ 无法适配屏幕，界面存在左右滑动的现象

**Comment by fecommunity** [comment]
> 微信端打开 https://blog.gaoredu.com/ 无法适配屏幕，界面存在左右滑动的现象

感谢反馈，后续我们会针对移动端进一步优化使用体验。

**Comment by fecommunity** [comment]
您反馈的问题当前移动端已优化，可前往体验：<https://blog.gaoredu.com/ >

**Comment by fecommunity** [comment]
> 微信端打开 https://blog.gaoredu.com/ 无法适配屏幕，界面存在左右滑动的现象

目前试了下移动端效果如下：

![图片](https://github.com/user-attachments/assets/6b0b482d-b68e-40d2-94d9-0f0dc6af5878)
