### ISSUE TITLE
如非原创，请明确出处https://github.com/fantasticit/wipi

### ISSUE THREAD

**Issue by escfex** [fecommunity/reactpress#9]
https://github.com/fantasticit/wipi

**Comment by fecommunity** [comment]
> https://github.com/fantasticit/wipi

亲爱的 [escfex]，

非常感谢您的关注和对ReactPress项目的支持！ReactPress项目在设计之初借鉴了多个优秀的Github开源项目，并对这些内容进行了深度优化和重构，以更好地适应我们的项目需求。

关于您提到的非原创内容出处问题，我们非常重视。在ReactPress项目中，我们尊重项目原创性，后续我们将尽力在文档中标注所有引用的内容。

同时，我们也非常欢迎您的参与和贡献！如果您对ReactPress项目有任何建议、意见或发现任何问题，都请随时与我们联系。您的反馈对我们非常重要，将帮助我们不断改进和完善项目。

再次感谢您的关注和支持！我们期待与您一起共建ReactPress项目，为开源社区做出更大的贡献！

祝好，

[fecommunity]

ReactPress项目团队
